apiVersion: v1
kind: Pod
metadata:
  name: my-first2-pod
  labels:
    app: Muhammad
spec:
  containers:
    - image: assnginx:alpine
      name: nginx-container
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "512Mi"
          cpu: "1"
        requests:
          memory: "100Mi"