on:
 push:
    branches:









jobs:
  build:
    runs-on: ubuntu-latest


    steps:

      - uses: actions/checkout@v3

      - name: 'login'
        run: docker login --username ${{secrets.USER}} --password ${{secrets.PASS}}

      - name: 'loggin'
        run: docker build -t ${{secrets.USER}}/imgtask .

      - name: 'push'
        run: docker push ${{secrets.USER}}/imgtask


